name: first run

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-22.04
    steps:
      - name: echo my name 
        run: echo "saravana kumar"
      - name: multiline script
        run:  |
          node -v
          npm -v
    